sudo: false
language: node_js
node_js: "5.1"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run clean
  - npm run dev
  - npm test
notifications:
  email:
    recipients:
      - daggerok@gmail.com
    on_failure: change # always
    on_success: never